# Configure notifications in Azure DevOps
trigger: none

pr: none

stages:
- stage: Run

  variables:
  - template: ./templates/variables/globals.yml

  jobs:
  - job: Run
    timeoutInMinutes: 120
    pool:
      name: azsdk-pool-mms-ubuntu-2204-general
      vmImage: MMSUbuntu22.04

    variables:
      Organization: azure-sdk
      Project: internal
      DotNetDevOpsFeed: "https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json"
      OutputPath: '$(Agent.BuildDirectory)/pipelineOwners.json'
    steps:
      - task: UseDotNet@2
        condition: eq(${{ parameters.SkipDotNetInstall }}, false)
        displayName: 'Use .NET Core sdk ${{ coalesce( parameters.DotNetCoreVersion, variables.DotNetCoreVersion) }}'
        inputs:
          version: '${{ coalesce( parameters.DotNetCoreVersion, variables.DotNetCoreVersion) }}'
              
      - task: AzureCLI@2
        displayName: Run Pipeline Owners Extractor
        workingDirectory: $(Build.SourcesDirectory)/${{parameters.ToolDirectory}}/Azure.Sdk.Tools.PipelineOwnersExtractor
        inputs:
          azureSubscription: 'Azure SDK Engineering System'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: dotnet run

      - publish: $(OutputPath)
        displayName: Publish pipelineOwners artifact
        artifact: pipelineOwners
        condition: succeededOrFailed()
