# Mirror the default branch for each repo folder to all subscribed langauge repos.

trigger: none
pr: none

pool:
  name: azsdk-pool-mms-ubuntu-2204-general
  vmImage: MMSUbuntu22.04

jobs:
  - job:
    displayName: Test Cosmos Emulator Install

    steps:
    - template: /eng/common/pipelines/templates/steps/cosmos-emulator.yml
      parameters:
        StartParameters: '/noexplorer /noui /enablepreview /EnableSqlComputeEndpoint /disableratelimiting /partitioncount=50 /consistency=Strong'
